### ISSUE TITLE
API Reference Documentation

### ISSUE THREAD

**Issue by vchrombie** [pytrello2/pytrello2#7]
Sphinx is a powerful and flexible tool specifically designed for documenting Python projects, and it works very well for generating API references. It can automatically generate documentation from docstrings in the code.

We can create a `docs/` folder for hosting the API documentation.

**Comment by theiiienrique** [comment]
Hi @vchrombie, is it okay if I take this issue? I'm relatively new to Python but have been learning and would love to contribute by helping set up the Sphinx documentation. Any guidance or tips would be greatly appreciated!

**Comment by vchrombie** [comment]
Hi @theiiienrique, please feel free to pick up. We are happy to have you contributing to the project.

You can read about sphinx here
- https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#quick-start
- https://tomasfarias.dev/articles/sphinx-docs-with-poetry-and-github-pages/
- https://coderefinery.github.io/documentation/gh_workflow/

The idea is to add sphinx to the project to generate documentation and maybe host it on github pages.

Please let me know if you need any help.

**Comment by theiiienrique** [comment]
Hi @vchrombie, so I've been able to generate most of the Sphinx documentation from the docstrings. The two that are giving me errors right now are `test_board.py` and `test_client.py`. It's saying it's because there isn't a `pytest` module to import.

Also, I'm having some trouble deploying to GitHub Pages. I think the `sphinx.yml` file I added to build the site is failing for some reason, so when it builds the site, it's only displaying the `README.md` file.

Any thoughts or suggestions? Also, let me know if you need more information.

**Comment by vchrombie** [comment]
Hi @theiiienrique 

> Hi @vchrombie, so I've been able to generate most of the Sphinx documentation from the docstrings. The two that are giving me errors right now are `test_board.py` and `test_client.py`. It's saying it's because there isn't a `pytest` module to import.

You can ignore the tests, we are only worried about the source code `pytrello2/` folder.

> Also, I'm having some trouble deploying to GitHub Pages. I think the `sphinx.yml` file I added to build the site is failing for some reason, so when it builds the site, it's only displaying the `README.md` file.

Did you push your code to your fork so that I can take a look?

**Comment by theiiienrique** [comment]
Okay, sounds good. And yes, I did!

**Comment by vchrombie** [comment]
@theiiienrique, please open a PR when you are ready. I can review it, get the PR merged to test it out on this repository and fix it later.

**Comment by vchrombie** [comment]
Thanks for helping with this issue @theiiienrique! 🚀 
We had a few issues with the permissions but I corrected them.

The docs are live at https://pytrello2.github.io/pytrello2 🎉
